'use client';

import { useMemo, useRef, useState } from 'react';
import {
  AlertTriangle, Archive, ArrowDownToLine, ArrowUpFromLine, Boxes, CalendarClock,
  Check, CircleDollarSign, Download, Edit3, FileText, Package, Plus, Search, Settings2,
  Trash2, Upload, UserRound, WalletCards
} from 'lucide-react';
import { useAccountingStore } from '@/lib/store';
import type { AccountingData, CheckRecord, Customer, InvoiceKind, Payment, Product } from '@/lib/types';
import { invoiceTotal, money, paidForInvoice, todayFa, uid } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Input, Textarea } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

function PageHead({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) {
  return <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{action}</div>;
}

function SearchBox({ value, onChange, placeholder = 'جستجو...' }: { value: string; onChange: (v: string) => void; placeholder?: string }) {
  return <div className="relative w-full max-w-sm"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input className="pr-9" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></div>;
}

export function InvoiceListView({ kind, onEdit, onNew }: { kind: InvoiceKind; onEdit: (id: string) => void; onNew: () => void }) {
  const { invoices, payments, deleteInvoice, settings } = useAccountingStore();
  const [q, setQ] = useState('');
  const [status, setStatus] = useState('all');
  const list = invoices.filter((i) => i.kind === kind).filter((i) => (i.number + ' ' + i.customerName).toLowerCase().includes(q.toLowerCase())).filter((i) => status === 'all' || i.status === status);
  const label = kind === 'sale' ? 'فاکتورهای فروش' : 'فاکتورهای خرید';
  return <div className="space-y-5">
    <PageHead title={label} subtitle="ثبت، جستجو، ویرایش و کنترل وضعیت فاکتورها" action={<Button onClick={onNew}><Plus className="h-4 w-4" /> {kind === 'sale' ? 'فاکتور فروش جدید' : 'فاکتور خرید جدید'}</Button>} />
    <Card><CardHeader className="flex-wrap"><SearchBox value={q} onChange={setQ} /><select className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">همه وضعیت‌ها</option><option value="draft">پیش‌نویس</option><option value="final">قطعی</option><option value="partial">بخشی تسویه</option><option value="settled">تسویه‌شده</option></select></CardHeader>
      <div className="table-wrap"><table className="data-table"><thead><tr><th>شماره</th><th>تاریخ</th><th>طرف حساب</th><th>وضعیت</th><th>مبلغ کل</th><th>پرداخت</th><th>مانده</th><th>عملیات</th></tr></thead><tbody>
        {list.map((i) => { const total = invoiceTotal(i); const paid = paidForInvoice(i.id, payments); return <tr key={i.id}><td className="font-black">{i.number}</td><td>{i.date}</td><td>{i.customerName || '—'}</td><td><InvoiceStatus status={i.status} /></td><td className="font-bold">{money(total)} <span className="text-[10px] text-slate-400">{settings.currency}</span></td><td>{money(paid)}</td><td className={total - paid > 0 ? 'font-bold text-rose-600' : 'font-bold text-emerald-600'}>{money(Math.max(0, total - paid))}</td><td><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => onEdit(i.id)} title="ویرایش"><Edit3 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-rose-600" onClick={() => confirm('فاکتور حذف شود؟') && deleteInvoice(i.id)} title="حذف"><Trash2 className="h-4 w-4" /></Button></div></td></tr>; })}
        {!list.length && <EmptyRow cols={8} text="فاکتوری مطابق فیلتر پیدا نشد." />}
      </tbody></table></div>
    </Card>
  </div>;
}

function InvoiceStatus({ status }: { status: string }) {
  const x: Record<string, [string, string]> = { draft: ['پیش‌نویس', 'bg-slate-100 text-slate-600'], final: ['قطعی', 'bg-sky-50 text-sky-700'], partial: ['بخشی تسویه', 'bg-amber-50 text-amber-700'], settled: ['تسویه‌شده', 'bg-emerald-50 text-emerald-700'] };
  const [label, cls] = x[status] || [status, '']; return <Badge className={cls}>{label}</Badge>;
}

export function CustomersView() {
  const { customers, invoices, payments, upsertCustomer, deleteCustomer, settings } = useAccountingStore();
  const [q, setQ] = useState(''); const [edit, setEdit] = useState<Customer | null>(null); const [open, setOpen] = useState(false);
  const list = customers.filter((c) => (c.name + ' ' + c.phone + ' ' + c.code).toLowerCase().includes(q.toLowerCase()));
  const balance = (id: string) => {
    const sales = invoices.filter((i) => i.customerId === id && i.kind === 'sale' && i.status !== 'draft').reduce((s, i) => s + invoiceTotal(i), 0);
    const purchase = invoices.filter((i) => i.customerId === id && i.kind === 'purchase' && i.status !== 'draft').reduce((s, i) => s + invoiceTotal(i), 0);
    const paid = payments.filter((p) => p.customerId === id).reduce((s, p) => s + p.amount, 0);
    return sales - paid - purchase;
  };
  const start = (c?: Customer) => { setEdit(c ? { ...c } : { id: uid('cus'), code: String(100000 + customers.length + 1), name: '', kind: 'customer', phone: '', address: '', nationalId: '', economicCode: '', postalCode: '' }); setOpen(true); };
  return <div className="space-y-5"><PageHead title="مشتریان و تامین‌کنندگان" subtitle="دفتر طرف حساب، مشخصات رسمی و مانده حساب" action={<Button onClick={() => start()}><Plus className="h-4 w-4" /> طرف حساب جدید</Button>} />
    <Card><CardHeader><SearchBox value={q} onChange={setQ} placeholder="نام، تلفن یا کد شخص..." /></CardHeader><div className="table-wrap"><table className="data-table"><thead><tr><th>کد</th><th>نام</th><th>نوع</th><th>تلفن</th><th>آدرس</th><th>مانده حساب</th><th>عملیات</th></tr></thead><tbody>{list.map((c) => { const b = balance(c.id); return <tr key={c.id}><td className="font-bold">{c.code}</td><td className="font-bold">{c.name}</td><td>{c.kind === 'customer' ? 'مشتری' : c.kind === 'supplier' ? 'تامین‌کننده' : 'هر دو'}</td><td>{c.phone || '—'}</td><td className="max-w-xs truncate">{c.address || '—'}</td><td className={b > 0 ? 'font-black text-rose-600' : b < 0 ? 'font-black text-emerald-600' : 'font-bold'}>{money(Math.abs(b))} {settings.currency}{b > 0 ? ' بدهکار' : b < 0 ? ' بستانکار' : ''}</td><td><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => start(c)}><Edit3 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-rose-600" onClick={() => confirm('طرف حساب حذف شود؟') && deleteCustomer(c.id)}><Trash2 className="h-4 w-4" /></Button></div></td></tr>; })}{!list.length && <EmptyRow cols={7} text="طرف حسابی پیدا نشد." />}</tbody></table></div></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle className="text-lg font-black">{edit && customers.some((c) => c.id === edit.id) ? 'ویرایش طرف حساب' : 'طرف حساب جدید'}</DialogTitle><DialogDescription className="text-sm text-slate-500">اطلاعات حقوقی برای فاکتور رسمی قابل استفاده است.</DialogDescription></DialogHeader>{edit && <div className="grid gap-3 sm:grid-cols-2"><Field label="نام *"><Input value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="کد شخص"><Input value={edit.code} onChange={(e) => setEdit({ ...edit, code: e.target.value })} /></Field><Field label="نوع"><select className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" value={edit.kind} onChange={(e) => setEdit({ ...edit, kind: e.target.value as Customer['kind'] })}><option value="customer">مشتری</option><option value="supplier">تامین‌کننده</option><option value="both">هر دو</option></select></Field><Field label="تلفن"><Input value={edit.phone} onChange={(e) => setEdit({ ...edit, phone: e.target.value })} /></Field><Field label="شناسه ملی"><Input value={edit.nationalId} onChange={(e) => setEdit({ ...edit, nationalId: e.target.value })} /></Field><Field label="کد اقتصادی"><Input value={edit.economicCode} onChange={(e) => setEdit({ ...edit, economicCode: e.target.value })} /></Field><Field label="کد پستی"><Input value={edit.postalCode} onChange={(e) => setEdit({ ...edit, postalCode: e.target.value })} /></Field><Field label="آدرس" className="sm:col-span-2"><Textarea value={edit.address} onChange={(e) => setEdit({ ...edit, address: e.target.value })} /></Field><div className="flex justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setOpen(false)}>انصراف</Button><Button disabled={!edit.name.trim()} onClick={() => { upsertCustomer(edit); setOpen(false); }}><Check className="h-4 w-4" /> ذخیره</Button></div></div>}</DialogContent></Dialog>
  </div>;
}

export function ProductsView() {
  const { products, upsertProduct, deleteProduct, settings } = useAccountingStore();
  const [q, setQ] = useState(''); const [edit, setEdit] = useState<Product | null>(null); const [open, setOpen] = useState(false);
  const list = products.filter((p) => (p.name + ' ' + p.code).toLowerCase().includes(q.toLowerCase()));
  const start = (p?: Product) => { setEdit(p ? { ...p } : { id: uid('prd'), code: String(1000 + products.length + 1), name: '', kind: 'product', unit: 'عدد', salePrice: 0, buyPrice: 0, stock: 0, minStock: 0 }); setOpen(true); };
  return <div className="space-y-5"><PageHead title="کالا و خدمات" subtitle="تعریف کالا، خدمت، قیمت خرید و فروش و حداقل موجودی" action={<Button onClick={() => start()}><Plus className="h-4 w-4" /> کالا / خدمت جدید</Button>} />
    <Card><CardHeader><SearchBox value={q} onChange={setQ} /></CardHeader><div className="table-wrap"><table className="data-table"><thead><tr><th>کد</th><th>نام</th><th>نوع</th><th>واحد</th><th>قیمت خرید</th><th>قیمت فروش</th><th>موجودی</th><th>عملیات</th></tr></thead><tbody>{list.map((p) => <tr key={p.id}><td className="font-bold">{p.code}</td><td className="font-bold">{p.name}</td><td><Badge className={p.kind === 'service' ? 'bg-violet-50 text-violet-700' : 'bg-sky-50 text-sky-700'}>{p.kind === 'service' ? 'خدمت' : 'کالا'}</Badge></td><td>{p.unit}</td><td>{money(p.buyPrice)}</td><td className="font-bold">{money(p.salePrice)} <span className="text-[10px] text-slate-400">{settings.currency}</span></td><td className={p.kind === 'product' && p.stock <= p.minStock ? 'font-black text-rose-600' : ''}>{p.kind === 'product' ? `${money(p.stock)} ${p.unit}` : '—'}</td><td><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => start(p)}><Edit3 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-rose-600" onClick={() => confirm('این مورد حذف شود؟') && deleteProduct(p.id)}><Trash2 className="h-4 w-4" /></Button></div></td></tr>)}{!list.length && <EmptyRow cols={8} text="کالا یا خدمتی پیدا نشد." />}</tbody></table></div></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle className="text-lg font-black">تعریف کالا / خدمت</DialogTitle><DialogDescription className="text-sm text-slate-500">خدمات روی موجودی انبار اثر نمی‌گذارند.</DialogDescription></DialogHeader>{edit && <div className="grid gap-3 sm:grid-cols-2"><Field label="نام *"><Input value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="کد"><Input value={edit.code} onChange={(e) => setEdit({ ...edit, code: e.target.value })} /></Field><Field label="نوع"><select className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" value={edit.kind} onChange={(e) => setEdit({ ...edit, kind: e.target.value as Product['kind'] })}><option value="product">کالا</option><option value="service">خدمت</option></select></Field><Field label="واحد"><Input value={edit.unit} onChange={(e) => setEdit({ ...edit, unit: e.target.value })} /></Field><Field label="قیمت خرید"><Input type="number" min="0" value={edit.buyPrice} onChange={(e) => setEdit({ ...edit, buyPrice: Number(e.target.value) })} /></Field><Field label="قیمت فروش"><Input type="number" min="0" value={edit.salePrice} onChange={(e) => setEdit({ ...edit, salePrice: Number(e.target.value) })} /></Field>{edit.kind === 'product' && <><Field label="موجودی اولیه / فعلی"><Input type="number" value={edit.stock} onChange={(e) => setEdit({ ...edit, stock: Number(e.target.value) })} /></Field><Field label="حداقل موجودی"><Input type="number" min="0" value={edit.minStock} onChange={(e) => setEdit({ ...edit, minStock: Number(e.target.value) })} /></Field></>}<div className="flex justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setOpen(false)}>انصراف</Button><Button disabled={!edit.name.trim()} onClick={() => { upsertProduct(edit); setOpen(false); }}>ذخیره</Button></div></div>}</DialogContent></Dialog>
  </div>;
}

export function InventoryView() {
  const { products, settings } = useAccountingStore(); const [q, setQ] = useState('');
  const list = products.filter((p) => p.kind === 'product').filter((p) => (p.name + p.code).toLowerCase().includes(q.toLowerCase()));
  const total = list.reduce((s, p) => s + p.stock * p.buyPrice, 0); const low = list.filter((p) => p.stock <= p.minStock).length;
  return <div className="space-y-5"><PageHead title="انبار" subtitle="موجودی کالا از روی فاکتورهای قطعی خرید و فروش به‌روزرسانی می‌شود" />
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={Boxes} title="تعداد اقلام" value={String(list.length)} /><Metric icon={Archive} title="ارزش موجودی" value={`${money(total)} ${settings.currency}`} /><Metric icon={AlertTriangle} title="زیر حداقل موجودی" value={String(low)} danger={low > 0} /></div>
    <Card><CardHeader><SearchBox value={q} onChange={setQ} /></CardHeader><div className="table-wrap"><table className="data-table"><thead><tr><th>کد</th><th>کالا</th><th>واحد</th><th>موجودی</th><th>حداقل</th><th>قیمت خرید</th><th>ارزش موجودی</th><th>وضعیت</th></tr></thead><tbody>{list.map((p) => <tr key={p.id}><td>{p.code}</td><td className="font-bold">{p.name}</td><td>{p.unit}</td><td className="font-black">{money(p.stock)}</td><td>{money(p.minStock)}</td><td>{money(p.buyPrice)}</td><td>{money(p.stock * p.buyPrice)}</td><td>{p.stock <= p.minStock ? <Badge className="bg-rose-50 text-rose-700">نیاز به تامین</Badge> : <Badge className="bg-emerald-50 text-emerald-700">مناسب</Badge>}</td></tr>)}{!list.length && <EmptyRow cols={8} text="کالایی برای نمایش نیست." />}</tbody></table></div></Card>
  </div>;
}

export function PaymentsView() {
  const { payments, customers, invoices, addPayment, deletePayment, settings } = useAccountingStore();
  const [open, setOpen] = useState(false); const [q, setQ] = useState('');
  const [form, setForm] = useState<Payment>({ id: '', customerId: '', invoiceId: '', method: 'cash', amount: 0, date: todayFa(), reference: '', notes: '' });
  const start = () => { setForm({ id: uid('pay'), customerId: '', invoiceId: '', method: 'cash', amount: 0, date: todayFa(), reference: '', notes: '' }); setOpen(true); };
  const name = (id: string) => customers.find((c) => c.id === id)?.name || '—'; const list = payments.filter((p) => (name(p.customerId) + ' ' + p.reference).toLowerCase().includes(q.toLowerCase()));
  return <div className="space-y-5"><PageHead title="دریافت و پرداخت" subtitle="ثبت تسویه نقدی، کارت و چک و اتصال به فاکتور" action={<Button onClick={start}><Plus className="h-4 w-4" /> ثبت تراکنش</Button>} />
    <Card><CardHeader><SearchBox value={q} onChange={setQ} /></CardHeader><div className="table-wrap"><table className="data-table"><thead><tr><th>تاریخ</th><th>طرف حساب</th><th>روش</th><th>فاکتور</th><th>مبلغ</th><th>مرجع</th><th>عملیات</th></tr></thead><tbody>{list.map((p) => <tr key={p.id}><td>{p.date}</td><td className="font-bold">{name(p.customerId)}</td><td>{p.method === 'cash' ? 'نقدی' : p.method === 'card' ? 'کارت / واریز' : 'چک'}</td><td>{invoices.find((i) => i.id === p.invoiceId)?.number || '—'}</td><td className="font-black text-emerald-700">{money(p.amount)} {settings.currency}</td><td>{p.reference || '—'}</td><td><Button variant="ghost" size="icon" className="text-rose-600" onClick={() => confirm('تراکنش حذف شود؟') && deletePayment(p.id)}><Trash2 className="h-4 w-4" /></Button></td></tr>)}{!list.length && <EmptyRow cols={7} text="تراکنشی ثبت نشده است." />}</tbody></table></div></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle className="text-lg font-black">ثبت دریافت / پرداخت</DialogTitle><DialogDescription className="text-sm text-slate-500">در صورت اتصال به فاکتور، وضعیت تسویه خودکار محاسبه می‌شود.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Field label="طرف حساب *"><select className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" value={form.customerId} onChange={(e) => setForm({ ...form, customerId: e.target.value, invoiceId: '' })}><option value="">انتخاب...</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="فاکتور مرتبط"><select className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" value={form.invoiceId || ''} onChange={(e) => setForm({ ...form, invoiceId: e.target.value })}><option value="">بدون اتصال</option>{invoices.filter((i) => !form.customerId || i.customerId === form.customerId).map((i) => <option key={i.id} value={i.id}>{i.number} - {money(invoiceTotal(i))}</option>)}</select></Field><Field label="روش"><select className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" value={form.method} onChange={(e) => setForm({ ...form, method: e.target.value as Payment['method'] })}><option value="cash">نقدی</option><option value="card">کارت / واریز</option><option value="check">چک</option></select></Field><Field label={`مبلغ (${settings.currency}) *`}><Input type="number" min="0" value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} /></Field><Field label="تاریخ"><Input value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></Field><Field label="شماره پیگیری / مرجع"><Input value={form.reference || ''} onChange={(e) => setForm({ ...form, reference: e.target.value })} /></Field><Field label="توضیحات" className="sm:col-span-2"><Textarea value={form.notes || ''} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><div className="flex justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setOpen(false)}>انصراف</Button><Button disabled={!form.customerId || form.amount <= 0} onClick={() => { addPayment(form); setOpen(false); }}>ثبت تراکنش</Button></div></div></DialogContent></Dialog>
  </div>;
}

export function ChecksView() {
  const { checks, customers, upsertCheck, deleteCheck, settings } = useAccountingStore(); const [open, setOpen] = useState(false); const [filter, setFilter] = useState('all');
  const [form, setForm] = useState<CheckRecord>({ id: '', direction: 'received', customerId: '', amount: 0, dueDate: '', number: '', bank: '', owner: '', status: 'pending', notes: '' });
  const start = (c?: CheckRecord) => { setForm(c ? { ...c } : { id: uid('chk'), direction: 'received', customerId: '', amount: 0, dueDate: '', number: '', bank: '', owner: '', status: 'pending', notes: '' }); setOpen(true); };
  const list = checks.filter((c) => filter === 'all' || c.status === filter); const customerName = (id: string) => customers.find((c) => c.id === id)?.name || '—';
  return <div className="space-y-5"><PageHead title="چک‌ها و سررسید" subtitle="چک‌های دریافتی و پرداختی، سررسید و وضعیت وصول" action={<Button onClick={() => start()}><Plus className="h-4 w-4" /> چک جدید</Button>} />
    <Card><CardHeader><div className="flex flex-wrap gap-2">{[['all','همه'],['pending','در انتظار'],['cleared','وصول شده'],['bounced','برگشتی']].map(([k,l]) => <Button key={k} variant={filter === k ? 'default' : 'outline'} size="sm" onClick={() => setFilter(k)}>{l}</Button>)}</div></CardHeader><div className="table-wrap"><table className="data-table"><thead><tr><th>نوع</th><th>طرف حساب</th><th>شماره چک</th><th>بانک</th><th>مبلغ</th><th>سررسید</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{list.map((c) => <tr key={c.id}><td>{c.direction === 'received' ? <span className="text-emerald-700">دریافتی</span> : <span className="text-rose-700">پرداختی</span>}</td><td className="font-bold">{customerName(c.customerId)}</td><td>{c.number}</td><td>{c.bank}</td><td className="font-black">{money(c.amount)} {settings.currency}</td><td>{c.dueDate || '—'}</td><td><CheckStatus status={c.status} /></td><td><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => start(c)}><Edit3 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-rose-600" onClick={() => confirm('چک حذف شود؟') && deleteCheck(c.id)}><Trash2 className="h-4 w-4" /></Button></div></td></tr>)}{!list.length && <EmptyRow cols={8} text="چکی در این وضعیت وجود ندارد." />}</tbody></table></div></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle className="text-lg font-black">ثبت / ویرایش چک</DialogTitle><DialogDescription className="text-sm text-slate-500">تاریخ سررسید را به قالب دلخواه شمسی ثبت کنید.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Field label="نوع"><select className="h-10 w-full rounded-xl border border-slate-200 px-3" value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value as CheckRecord['direction'] })}><option value="received">دریافتی</option><option value="issued">پرداختی</option></select></Field><Field label="طرف حساب"><select className="h-10 w-full rounded-xl border border-slate-200 px-3" value={form.customerId} onChange={(e) => setForm({ ...form, customerId: e.target.value })}><option value="">انتخاب...</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="شماره چک"><Input value={form.number} onChange={(e) => setForm({ ...form, number: e.target.value })} /></Field><Field label="بانک"><Input value={form.bank} onChange={(e) => setForm({ ...form, bank: e.target.value })} /></Field><Field label="صاحب چک"><Input value={form.owner} onChange={(e) => setForm({ ...form, owner: e.target.value })} /></Field><Field label={`مبلغ (${settings.currency})`}><Input type="number" min="0" value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} /></Field><Field label="سررسید"><Input value={form.dueDate} placeholder="۱۴۰۵/۰۴/۱۵" onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></Field><Field label="وضعیت"><select className="h-10 w-full rounded-xl border border-slate-200 px-3" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as CheckRecord['status'] })}><option value="pending">در انتظار</option><option value="cleared">وصول شده</option><option value="bounced">برگشتی</option></select></Field><div className="flex justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setOpen(false)}>انصراف</Button><Button disabled={!form.customerId || form.amount <= 0} onClick={() => { upsertCheck(form); setOpen(false); }}>ذخیره</Button></div></div></DialogContent></Dialog>
  </div>;
}

function CheckStatus({ status }: { status: CheckRecord['status'] }) { return status === 'cleared' ? <Badge className="bg-emerald-50 text-emerald-700">وصول شده</Badge> : status === 'bounced' ? <Badge className="bg-rose-50 text-rose-700">برگشتی</Badge> : <Badge className="bg-amber-50 text-amber-700">در انتظار</Badge>; }

export function ReportsView() {
  const { invoices, payments, products, checks, settings } = useAccountingStore();
  const sales = invoices.filter((i) => i.kind === 'sale' && i.status !== 'draft').reduce((s, i) => s + invoiceTotal(i), 0); const purchases = invoices.filter((i) => i.kind === 'purchase' && i.status !== 'draft').reduce((s, i) => s + invoiceTotal(i), 0); const paid = payments.reduce((s, p) => s + p.amount, 0); const stock = products.filter((p) => p.kind === 'product').reduce((s, p) => s + p.stock * p.buyPrice, 0); const pending = checks.filter((c) => c.status === 'pending').reduce((s, c) => s + c.amount, 0);
  const rows = [ ['فروش قطعی', sales], ['خرید قطعی', purchases], ['مجموع دریافت/پرداخت ثبت‌شده', paid], ['ارزش موجودی کالا', stock], ['چک‌های در انتظار', pending] ] as const;
  const max = Math.max(...rows.map((x) => x[1]), 1);
  return <div className="space-y-5"><PageHead title="گزارش‌ها" subtitle="خلاصه مالی و عملیاتی از داده‌های ثبت‌شده در مرورگر" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{rows.map(([label, value]) => <Card key={label}><CardContent><div className="text-xs font-bold text-slate-500">{label}</div><div className="mt-2 text-xl font-black">{money(value)} <span className="text-[10px] text-slate-400">{settings.currency}</span></div></CardContent></Card>)}</div><Card><CardHeader><CardTitle>مقایسه شاخص‌ها</CardTitle></CardHeader><CardContent className="space-y-5">{rows.map(([label, value]) => <div key={label}><div className="mb-2 flex justify-between text-sm"><span className="font-bold">{label}</span><span>{money(value)}</span></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-sky-500" style={{ width: `${Math.max(2, (value / max) * 100)}%` }} /></div></div>)}</CardContent></Card></div>;
}

export function SettingsView() {
  const store = useAccountingStore(); const { settings, setSettings, replaceAll, resetAll } = store; const fileRef = useRef<HTMLInputElement>(null); const [draft, setDraft] = useState(settings);
  const exportData = () => { const data: AccountingData = { customers: store.customers, products: store.products, invoices: store.invoices, payments: store.payments, checks: store.checks, settings: store.settings }; const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `accountants-backup-${Date.now()}.json`; a.click(); URL.revokeObjectURL(a.href); };
  const importData = async (file?: File) => { if (!file) return; try { const parsed = JSON.parse(await file.text()) as AccountingData; if (!parsed.customers || !parsed.products || !parsed.invoices || !parsed.settings) throw new Error('invalid'); replaceAll(parsed); setDraft(parsed.settings); alert('نسخه پشتیبان با موفقیت بازیابی شد.'); } catch { alert('فایل پشتیبان معتبر نیست.'); } };
  return <div className="space-y-5"><PageHead title="تنظیمات" subtitle="اطلاعات کسب‌وکار، فاکتور رسمی و نسخه پشتیبان" />
    <div className="grid gap-5 xl:grid-cols-[1fr_.72fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-sky-600" /> اطلاعات کسب‌وکار و فاکتور</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Field label="نام کسب‌وکار"><Input value={draft.businessName} onChange={(e) => setDraft({ ...draft, businessName: e.target.value })} /></Field><Field label="نام صاحب حساب"><Input value={draft.ownerName} onChange={(e) => setDraft({ ...draft, ownerName: e.target.value })} /></Field><Field label="تلفن"><Input value={draft.phone} onChange={(e) => setDraft({ ...draft, phone: e.target.value })} /></Field><Field label="عنوان فاکتور فروش"><Input value={draft.invoiceTitle} onChange={(e) => setDraft({ ...draft, invoiceTitle: e.target.value })} /></Field><Field label="شناسه ملی"><Input value={draft.nationalId} onChange={(e) => setDraft({ ...draft, nationalId: e.target.value })} /></Field><Field label="کد اقتصادی"><Input value={draft.economicCode} onChange={(e) => setDraft({ ...draft, economicCode: e.target.value })} /></Field><Field label="کد پستی"><Input value={draft.postalCode} onChange={(e) => setDraft({ ...draft, postalCode: e.target.value })} /></Field><Field label="واحد پول"><select className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" value={draft.currency} onChange={(e) => setDraft({ ...draft, currency: e.target.value as 'تومان' | 'ریال' })}><option value="تومان">تومان</option><option value="ریال">ریال</option></select></Field><Field label="شماره کارت"><Input value={draft.cardNumber} onChange={(e) => setDraft({ ...draft, cardNumber: e.target.value })} /></Field><Field label="شماره شبا"><Input value={draft.iban} onChange={(e) => setDraft({ ...draft, iban: e.target.value })} /></Field><Field label="آدرس" className="sm:col-span-2"><Textarea value={draft.address} onChange={(e) => setDraft({ ...draft, address: e.target.value })} /></Field><Field label="پاورقی فاکتور" className="sm:col-span-2"><Textarea value={draft.footer} onChange={(e) => setDraft({ ...draft, footer: e.target.value })} /></Field><div className="sm:col-span-2 flex justify-end"><Button onClick={() => setSettings(draft)}>ذخیره تنظیمات</Button></div></CardContent></Card>
      <div className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Download className="h-5 w-5 text-sky-600" /> پشتیبان‌گیری</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-slate-600"><p>تمام داده‌ها در LocalStorage مرورگر نگهداری می‌شوند. برای انتقال به سیستم دیگر خروجی JSON بگیرید.</p><div className="grid gap-2"><Button variant="outline" onClick={exportData}><ArrowDownToLine className="h-4 w-4" /> دانلود نسخه پشتیبان</Button><Button variant="outline" onClick={() => fileRef.current?.click()}><ArrowUpFromLine className="h-4 w-4" /> بازیابی نسخه پشتیبان</Button><input ref={fileRef} type="file" className="hidden" accept="application/json" onChange={(e) => importData(e.target.files?.[0])} /></div></CardContent></Card><Card><CardHeader><CardTitle className="text-rose-700">بازنشانی داده‌ها</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-slate-600">داده‌های فعلی با نمونه اولیه جایگزین می‌شوند.</p><Button variant="danger" onClick={() => confirm('همه داده‌ها بازنشانی شوند؟') && resetAll()}><Trash2 className="h-4 w-4" /> بازنشانی کامل</Button></CardContent></Card></div>
    </div>
  </div>;
}

function Field({ label, children, className = '' }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`space-y-1.5 ${className}`}><span className="block text-xs font-bold text-slate-600">{label}</span>{children}</label>; }
function EmptyRow({ cols, text }: { cols: number; text: string }) { return <tr><td colSpan={cols} className="!py-14 text-center text-slate-400">{text}</td></tr>; }
function Metric({ icon: Icon, title, value, danger = false }: { icon: typeof Boxes; title: string; value: string; danger?: boolean }) { return <Card><CardContent className="flex items-center gap-4"><div className={`grid h-11 w-11 place-items-center rounded-xl ${danger ? 'bg-rose-50 text-rose-600' : 'bg-sky-50 text-sky-600'}`}><Icon className="h-5 w-5" /></div><div><div className="text-xs font-bold text-slate-500">{title}</div><div className={`mt-1 text-xl font-black ${danger ? 'text-rose-700' : ''}`}>{value}</div></div></CardContent></Card>; }
